<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGteAPAv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGteAPAv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGteAPAv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGteAPAv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGteAPAv\App_KernelDevDebugContainer([
    'container.build_hash' => 'GteAPAv',
    'container.build_id' => '22fd5952',
    'container.build_time' => 1680262459,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGteAPAv');
